### ISSUE TITLE
Logo/Favicon

### ISSUE THREAD

**Issue by jokosanyang** [jokosanyang/TicTacOrToe#9]
Create one in Google Drawings and export as SVG. 
A nought and cross overlapped somehow?

**Comment by jokosanyang** [comment]
![logo](https://user-images.githubusercontent.com/43584074/62894747-45072500-bd45-11e9-87f4-c2754848570c.jpg)

**Comment by jokosanyang** [comment]
Shoutout to @tloth for the logo! <3

**Comment by tloth** [comment]
:sob: :sparkles:
